services:

  nginxproxymanager:
    container_name: nginxproxymanager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '88:80'
      - '81:81'
      - '443:443'
    volumes:
      - /appdata/nginx/data:/data
      - /appdata/nginx/letsencrypt:/etc/letsencrypt
    healthcheck:
      test: [ "CMD", "/bin/check-health" ]
      interval: 10s
      timeout: 3s

  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /appdata/homarr/configs:/app/data/configs
      - /appdata/homarr/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock # enable access to docker
  #    ports:
  #      - '7575:7575'

  dash:
    container_name: dash
    image: mauricenino/dashdot:latest
    restart: unless-stopped
    privileged: true
    environment:
      DASHDOT_ENABLE_CPU_TEMPS: 'true'
      DASHDOT_SHOW_HOST: 'true'
      DASHDOT_ENABLE_STORAGE_SPLIT_VIEW: 'true'
      DASHDOT_PAGE_TITLE: rpi-omv
      DASHDOT_ACCEPT_OOKLA_EULA: 'true'
    #    ports:
    #      - '3002:3001'
    volumes:
      - /appdata/dash:/mnt/host:ro

  uptime-kuma:
    # 1 is the last version
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1
    volumes:
      - /appdata/uptime-kuma/data:/app/data
    #    ports:
    #      - "3001:3001"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

  yacht:
    container_name: yacht
    image: selfhostedpro/yacht
    restart: unless-stopped
    #    ports:
    #      - "8001:8000"
    volumes:
      - /appdata/yacht/config:/config
      - /var/run/docker.sock:/var/run/docker.sock

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    environment:
      - TZ=Europe/Bucharest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    #    ports:
    #      - "9999:8080"
    networks:
      - default

  ouroboros:
    container_name: ouroboros
    image: pyouroboros/ouroboros
    environment:
      - CLEANUP=true
      - INTERVAL=86400
      - LOG_LEVEL=info
      - SELF_UPDATE=true
      - TZ=Europe/Bucharest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default

networks:
  default:
    external: true
    name: nginx_network