version: "3.8"
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    environment:
      - TZ=Europe/Bucharest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    ports:
      - "9999:8080"
    networks:
      - default
  ouroboros:
    container_name: ouroboros
    image: pyouroboros/ouroboros
    environment:
      - CLEANUP=true
      - INTERVAL=86400
      - LOG_LEVEL=info
      - SELF_UPDATE=true
      - TZ=Europe/Bucharest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default
networks:
  default:
    external: true
    name: nginx_network
