services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host           #needs to run like this, otherwise if ran inside docker network
    environment:                 #the client would not recognize the server, also it exposes lots of ports
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
      - VERSION=docker
    volumes:
      - /appdata/plex/config:/config
      - /srv/dev-disk-by-uuid-927de304-fe4e-430d-8c9d-97e019fe287f/movies:/movies
      - /srv/dev-disk-by-uuid-927de304-fe4e-430d-8c9d-97e019fe287f/tv_shows/:/tv