version: '3.8'

services:
  dash:
    container_name: dash
    image: mauricenino/dashdot:latest
    restart: unless-stopped
    privileged: true
    environment:
      DASHDOT_ENABLE_CPU_TEMPS: 'true'
      DASHDOT_SHOW_HOST: 'true'
      DASHDOT_ENABLE_STORAGE_SPLIT_VIEW: 'true'
      DASHDOT_PAGE_TITLE: rpi-omv
      DASHDOT_ACCEPT_OOKLA_EULA: 'true'
    ports:
      - '3002:3001'
    volumes:
      - /appdata/dash:/mnt/host:ro

networks:
  default:
    external: true
    name: nginx_network
