# https://github.com/NginxProxyManager/nginx-proxy-manager
# http://<docker-host>:81
#
#  Default Admin User:
#  Email:    admin@example.com
#  Password: changeme

version: '3.8'
services:
  nginxproxymanager:
    container_name: nginxproxymanager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '88:80'
      - '81:81'
      - '443:443'
    volumes:
      - /appdata/nginx/data:/data
      - /appdata/nginx/letsencrypt:/etc/letsencrypt
    healthcheck:
      test: [ "CMD", "/bin/check-health" ]
      interval: 10s
      timeout: 3s
networks:
  default:
    name: nginx_network
