version: "3.8"
services:
  yacht:
    container_name: yacht
    image: selfhostedpro/yacht
    restart: unless-stopped
    ports:
      - "8001:8000"
    volumes:
      - /appdata/yacht/config:/config
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    external: true
    name: nginx_network
