version: "3.8"
services:
  bazarr:
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    volumes:
      - /appdata/bazarr/config:/config
      # sudo chmod -R 0777 .   -> to add rights to the folder
      - /srv/dev-disk-by-uuid-1818fef1-b311-4d1d-8378-3745d8e7a331/cloud_500gb:/movies
    ports:
      - "6767:6767"
    restart: unless-stopped

networks:
  default:
    external: true
    name: nginx_network