services:
  bazarr:
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    volumes:
      - /appdata/bazarr/config:/config
      # sudo chmod -R 0777 .   -> to add rights to the folder
      - /srv/dev-disk-by-uuid-927de304-fe4e-430d-8c9d-97e019fe287f/movies:/movies
    ports:
      - "6767:6767"
    restart: unless-stopped

networks:
  default:
    external: true
    name: nginx_network