version: "3.8"
services:
  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    environment:
      - PUID=111
      - PGID=321
      - UMASK=002
      - TZ=Europe/Bucharest
    volumes:
      - /appdata/radarr/data:/config
      - /srv/dev-disk-by-uuid-1818fef1-b311-4d1d-8378-3745d8e7a331/cloud_500gb:/movies #optional
    ports:
      - "7878:7878"
    restart: unless-stopped

networks:
  default:
    external: true
    name: nginx_network
