services:
  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    volumes:
      - /appdata/radarr/data:/config
      - /srv/dev-disk-by-uuid-927de304-fe4e-430d-8c9d-97e019fe287f/movies:/movies #optional
    ports:
      - "7878:7878"
    restart: unless-stopped

networks:
  default:
    external: true
    name: nginx_network
