services:
  homebridge:
    container_name: homebridge
    image: oznu/homebridge:ubuntu
    restart: always
    network_mode: host
    environment:
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
    ports:
      - "8581:8581"
    volumes:
      - /appdata/homebridge:/homebridge

networks:
  default:
    external: true
    name: nginx_network
